<?php
$this->registerEducationRepository();
$this->registerExperienceRepository();
$this->registerSkillRepository();
$this->registerPortfolioRepository();
$this->registerAboutRepository();
$this->registerMessageRepository();
$this->registerSlideRepository();
$this->registerSocialRepository();